/* CONSTRAINT FOR FLASHCARD DB */



ALTER TABLE USER ADD CONSTRAINT PK_USER PRIMARY KEY (EMAIL);


ALTER TABLE CATEGORY ADD CONSTRAINT PK_CATEGORY PRIMARY KEY (U_EMAIL, TITLE);
ALTER TABLE CATEGORY ADD CONSTRAINT FK_CATEGORY_USER FOREIGN KEY (U_EMAIL) REFERENCES USER(EMAIL);


ALTER TABLE QUESTION ADD CONSTRAINT PK_QUESTION PRIMARY KEY (C_TITLE, U_EMAIL, TITLE);
ALTER TABLE QUESTION ADD CONSTRAINT FK_QUESTION_USER FOREIGN KEY (U_EMAIL) REFERENCES USER(EMAIL);
ALTER TABLE QUESTION ADD CONSTRAINT FK_QUESTION_CATEGORY FOREIGN KEY (C_TITLE) REFERENCES CATEGORY(TITLE);
